apiVersion: v1
kind: Secret
metadata:
  name: velero-repo-credentials
  namespace: velero
type: Opaque
stringData:
  # Key 1: For S3 Connection (AWS Plugin)
  cloud: |
    [default]
    aws_access_key_id=minio
    aws_secret_access_key=minio123
  
  # Key 2: For Data Encryption (Kopia/Node Agent)
  repository-password: "fOUkEqqQbLlfvS6aM8KM1+LzeYGQEaNysiukzgNDjGo="
