apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:12
        securityContext:
          privileged: true
        env:
          - name: SHARED_DIRECTORY
            value: /exports
        ports:
          - name: nfs
            containerPort: 2049
          - name: rpcbind
            containerPort: 111
          - name: mountd
            containerPort: 20048
        volumeMounts:
          - name: export-volume
            mountPath: /exports
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/nfs-data
            type: DirectoryOrCreate