apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
  namespace: nfs-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi # Le nom défini dans ton nfs-values.yaml
  resources:
    requests:
      storage: 1Mi